esphome:
  includes:
    - wiegand_device.h
  name: door_reader
  platform: ESP32
  board: esp32doit-devkit-v1


time:
  #- platform: homeassistant
  - platform: sntp
    id: sntp_time
    servers:  [0.pool.ntp.org, 1.pool.ntp.org , 2.pool.ntp.org]

custom_component:
  - lambda: |-
       auto wiegand = new WiegandReader(21, 23, "door1");
       return {wiegand};
